name: Keep Hugging Face Spaces Awake

on:
  schedule:
    - cron: '0 0 * * *'  # This runs the job every day at midnight UTC
  workflow_dispatch:

jobs:
  keep-awake:
    runs-on: ubuntu-latest
    
    steps:
      - name: Send API request to Hospital Space
        run: curl -X GET "https://fsbxcm-gemini2api.hf.space/"
        
      - name: Send API request to Facebook Sentiment Analysis Space
        run: curl -X GET "https://fsbxcm-grok2api.hf.space/login"
        
      - name: Send API request to Hotel Space
        run: curl -X GET "https://fsbxcm-oneapi.hf.space/"
